apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: payments-api-runtime-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: payments-api-runtime-secrets
  data:
    - secretKey: PAYOUT_PROVIDER_TOKEN
      remoteRef:
        key: payments-api/payout-provider-token
