apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: payments-refunds
  namespace: payments
spec:
  parentRefs:
    - name: kong
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /refunds
      backendRefs:
        - name: payment-api
          port: 80

